test('Fail test', () => {
    throw new Error('This test always fails');
});